//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBinhLuan
    {
        public int MaBinhLuan { get; set; }
        public string NoiDungBL { get; set; }
        public System.DateTime ThoiGianBL { get; set; }
        public int MaNguoiDung { get; set; }
        public int MaSanPham { get; set; }
    
        public virtual tblNguoiDung tblNguoiDung { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
