//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDonHang()
        {
            this.tblChiTietDonHangs = new HashSet<tblChiTietDonHang>();
        }
    
        public int MaDonHang { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietDonHang> tblChiTietDonHangs { get; set; }
        public virtual tblNguoiDung tblNguoiDung { get; set; }
        public virtual tblTrangThai tblTrangThai { get; set; }
    }
}
