//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblNhaCungCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhaCungCap()
        {
            this.tblPhieuNhaps = new HashSet<tblPhieuNhap>();
            this.tblSanPhams = new HashSet<tblSanPham>();
        }
    
        [Key]
        public int MaNCC { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập tên nhà cung cấp!")]
        public string TenNCC { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ nhà cung cấp!")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại nhà cung cấp!")]
        [RegularExpression(@"[0-9]{10}", ErrorMessage ="Số điện thoại không đúng!")]
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhieuNhap> tblPhieuNhaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSanPham> tblSanPhams { get; set; }
    }
}
